"""The test cases: the whole one- and two-byte space, and the Unicode scalar values to encode."""

from __future__ import annotations

import hashlib
from pathlib import Path

PLANE2 = range(0x20000, 0x30000)


def decode_cases() -> list[bytes]:
    """Every single byte, then every two-byte sequence, in numeric order (65 792 cases)."""
    singles = [bytes([b]) for b in range(256)]
    pairs = [bytes([lead, trail]) for lead in range(256) for trail in range(256)]
    return singles + pairs


def base_encode_cases() -> list[tuple[int, ...]]:
    """Every BMP scalar value and every plane-2 code point (CJK Extensions B to F)."""
    bmp = [(c,) for c in range(0x10000) if not 0xD800 <= c <= 0xDFFF]
    return bmp + [(c,) for c in PLANE2]


def _in_base(seq: tuple[int, ...]) -> bool:
    return len(seq) == 1 and (seq[0] < 0x10000 or seq[0] in PLANE2)


def encode_cases(extra: list[tuple[int, ...]]) -> list[tuple[int, ...]]:
    """Base cases plus extra sequences (code points outside the base ranges and multi-code-point
    sequences that some decoder produced), sorted after the base cases."""
    more = sorted({tuple(s) for s in extra if not _in_base(tuple(s))}, key=lambda s: (len(s), s))
    return base_encode_cases() + more


def read_extra(path: Path) -> list[tuple[int, ...]]:
    if not path.exists():
        return []
    out = []
    for line in path.read_text().splitlines():
        line = line.strip()
        if line and not line.startswith("#"):
            out.append(tuple(int(x, 16) for x in line.split()))
    return out


def write_extra(path: Path, extra: list[tuple[int, ...]]) -> None:
    rows = sorted({tuple(s) for s in extra if not _in_base(tuple(s))}, key=lambda s: (len(s), s))
    lines = [
        "# Encode cases beyond the BMP and plane 2: code point sequences that some decoder in this",
        "# study produced (multi-code-point mappings and code points outside the base ranges).",
        "# Generated by `python3 -m big5matrix run`; one sequence per line.",
    ]
    lines += [" ".join(f"{c:04X}" for c in s) for s in rows]
    path.write_text("\n".join(lines) + "\n")


def case_digest(args: list[str]) -> str:
    h = hashlib.sha256()
    for a in args:
        h.update(a.encode())
        h.update(b"\n")
    return h.hexdigest()
